### PR TITLE
Replace fixed sleeps in TodoApp E2E suite with state-based waits

### LINKED ISSUE #9: Replace fixed sleeps in TodoApp E2E suite with state-based waits
## Summary
The TodoApp Playwright suite in `Test/Framework/TestWebApplication/e2e-todo-tests.js` still contains repeated fixed `waitForTimeout(...)` calls. That makes the suite slower than necessary and more brittle as more cases are added.

## Scope
- Replace repeated fixed sleeps with DOM- or app-state-based waits.
- Prefer existing helpers where possible, and extract shared polling helpers where needed.
- Keep the suite behavior the same while reducing fixed runtime.

## Context
- Follow-up from PR #7 review feedback.
- Some targeted waits were already reduced while stabilizing the subtask persistence regression, but the file still needs a broader cleanup pass.

### PR DESCRIPTION
**Pull request by gautam-achieveai**
## Summary
- Replaces all 43 `waitForTimeout()` fixed-sleep calls in `e2e-todo-tests.js` with state-based polling/wait alternatives
- Adds 2 new helper functions: `waitForFolderHeader` (polls `.current-folder-name` text) and `waitForCallContext` (polls `window.__callContext.getCurrent()`)
- Uses existing helpers (`waitForDetailPane`, `waitForClassState`, `waitForSelectorCount`, `waitForTodoCount`) for the remaining replacements

## What changed
| Category | Count | Replacement strategy |
|----------|-------|---------------------|
| Detail pane open | 9 | `waitForDetailPane(page, s)` |
| CSS class toggle | 11 | `waitForClassState()` or `page.waitForFunction()` on element handle |
| Folder navigation | 8 | `waitForFolderHeader()` + `waitForSelectorCount()` |
| CallContext creation | 9 | `waitForCallContext()` with `'non-null'` or `'traceId!='` predicate |
| IndexedDB persistence | 2 | Removed redundant sleep (polling helper follows), or `waitForSelectorCount()` |
| Async task settlement | 2 | `waitForCallContext()` with traceId exclusion |
| Drag-and-drop | 2 | Removed (synchronous dispatch), folder-click wait covers state update |

## Test plan
- [x] All 50 E2E tests pass (verified with 3 consecutive runs)
- [x] Zero `waitForTimeout` calls remain in the file
- [x] JavaScript syntax check passes (`node --check`)
- [x] 2 self-review iterations completed, findings addressed

Closes #9

### CODE REVIEW

**Comment by gautam-achieveai** [comment]
Closing: this PR was created without explicit human approval due to a self-approval bug in the daemon (plan comment contained approval keywords). The fix has been applied. Will re-create after proper approval.

File: Test/Framework/TestWebApplication/e2e-todo-tests.js [hunk 1]
```diff
@@ -194,6 +194,36 @@ function sel(classMap, selector) {
...
+      throw new Error('waitForCallContext: traceId!= predicate requires a non-empty old traceId');
+    }
+    await page.waitForFunction(
+      (predStr) => {
+        const ctx = window.__callContext ? window.__callContext.getCurrent() : null;
+        if (predStr === 'non-null') return ctx !== null;
+        if (predStr.startsWith('traceId!=')) {
+          return ctx !== null && ctx.traceId !== predStr.slice(9);
+        }
+        return ctx !== null;
```
Comment (gautam-achieveai) [inline Test/Framework/TestWebApplication/e2e-todo-tests.js:212]: **[Gautam's review bot]** **[MEDIUM]** Silent fallback for unknown predicates.

Line 220 (`return ctx !== null;`) is a catch-all that duplicates the `'non-null'` branch. If someone passes a typo'd predicate (e.g., `'traceID!='` instead of `'traceId!='`), it silently succeeds without checking what it should.

**Suggestion — split into two focused functions:**

```javascript
async function waitForCallContext(page, timeout = 10000) {
  await page.waitForFunction(
    () => {
      const ctx = window.__callContext ? window.__callContext.getCurrent() : null;
      return ctx !== null;
    },
    { timeout }
  );
}

async function waitForNewCallContext(page, oldTraceId, timeout = 10000) {
  await page.waitForFunction(
    (oldId) => {
      const ctx = window.__callContext ? window.__callContext.getCurrent() : null;
      return ctx !== null && ctx.traceId !== oldId;
    },
    oldTraceId,
    { timeout }
  );
}
```

Call sites change from `waitForCallContext(page, 'traceId!=' + ctx1.traceId)` to `waitForNewCallContext(page, ctx1.traceId)` — reads more clearly, catches typos at the parameter level, and eliminates the guard clause + string parsing.

File: Test/Framework/TestWebApplication/e2e-todo-tests.js [hunk 2]
```diff
@@ -698,12 +741,12 @@ function sel(classMap, selector) {
...
     // Simulate drag-and-drop: 2nd todo (index 1) to My Day folder (index 0)
     await simulateDragDrop(page, s('.todo-item'), s('.folder-item'), 1, 0);
-    await page.waitForTimeout(500);
 
     // Switch to My Day folder to verify the todo now appears
     const folders = await page.$$(s('.folder-item'));
     await folders[0].click();
-    await page.waitForTimeout(500);
+    await waitForFolderHeader(page, s, 'My Day');
+    await waitForSelectorCount(page, s('.todo-item'));
```
Comment (gautam-achieveai) [inline Test/Framework/TestWebApplication/e2e-todo-tests.js]: **[Gautam's review bot]** **[MEDIUM]** Potential race condition — `waitForSelectorCount` returns immediately here.

"My Day" already contains "Buy groceries" (`IsMyDay=true` in sample data), so `waitForSelectorCount(page, s('.todo-item'))` with default `minCount=1` resolves immediately without waiting for the dragged todo to appear.

If the drag-drop's side effects (observable notifications, IndexedDB write) haven't propagated yet when the assertion on line 750 runs, the test would fail intermittently.

**Suggestion:** Use the existing `waitForTodoTitle` helper for a semantically precise wait:

```javascript
await waitForFolderHeader(page, s, 'My Day');
await waitForTodoTitle(page, s, 'Read a book');  // waits for the specific dragged todo
```

Same applies to the Important folder drag test at line 766.

File: Test/Framework/TestWebApplication/e2e-todo-tests.js [hunk 3]
```diff
@@ -620,12 +652,21 @@ function sel(classMap, selector) {
...
+    await waitForDetailPane(page, s);
     const title1 = await page.$eval(s('.detail-title-input'), el => el.value);
 
     // Select second todo
     await todos[1].click();
-    await page.waitForTimeout(500);
+    await waitForDetailPane(page, s);
+    // Wait for the title input value to actually change from the first todo's title
+    await page.waitForFunction(
+      ({ sel, oldTitle }) => {
```
Comment (gautam-achieveai) [inline Test/Framework/TestWebApplication/e2e-todo-tests.js]: **[Gautam's review bot]** **[LOW]** Minor: parameter name `sel` is inconsistent with the rest of the file, which uses `selector`. Consider renaming to `{ selector, oldTitle }` for consistency.

**Review by gautam-achieveai — COMMENTED** [review]
**[Gautam's review bot]** PR !22 Review — Replace fixed sleeps in TodoApp E2E suite with state-based waits

## Summary

This PR replaces all 43 `waitForTimeout()` calls in the E2E test suite with deterministic, state-based wait alternatives. Two new helpers are introduced (`waitForFolderHeader`, `waitForCallContext`) and existing helpers (`waitForDetailPane`, `waitForClassState`, `waitForSelectorCount`) are leveraged throughout. The second commit addresses self-review feedback with a defensive guard clause and a BUG-011 race fix.

**Linked Issue**: #9

## Verdict: APPROVE WITH COMMENTS

| Severity | Count |
|----------|-------|
| Critical | 0 |
| High | 0 |
| Medium | 2 |
| Low | 2 |

The PR is a clear quality improvement. All fixed sleeps are eliminated and the new helpers are well-structured. Two medium-severity items are worth addressing to prevent potential test flakiness, but are non-blocking.

## Findings

### [MEDIUM] `waitForCallContext` silent fallback for unknown predicates (line 220)
The catch-all `return ctx !== null` means any unrecognized predicate string silently behaves as `'non-null'`. A typo like `'traceID!='` instead of `'traceId!='` would pass without error, masking a test logic bug. See inline comment for suggested fix.

### [MEDIUM] Drag-drop tests may be racy (lines 749, 766)
`waitForSelectorCount(page, s('.todo-item'))` with default `minCount=1` returns immediately when the target folder already contains items (e.g., "My Day" has "Buy groceries"). The dragged todo ("Read a book") may not have appeared yet when the assertion runs. See inline comment.

### [LOW] Parameter naming inconsistency (line 663)
Uses `{ sel, oldTitle }` while all other helpers use `{ selector, ... }`. See inline comment.

### [LOW] 5 inline importance-class waits are repetitive (lines 790, 810, 820, 916, 918)
All do `page.waitForFunction(el => el.className.includes('important'), elementHandle, ...)`. Could share a helper, but acceptable as-is since they use ElementHandles (can't reuse `waitForClassState`).

## What's Good

- Complete elimination of all 43 `waitForTimeout()` calls — zero remain
- `waitForFolderHeader` is clean and follows existing helper patterns
- Self-review commit shows good attention to edge cases (guard clause, BUG-011 value-change race)
- CI passes
- No temporary code, debugging artifacts, or accidental inclusions

## Review Agents Used
- `temp-code-review`: Clean — no issues
- `code-simplifier`: Identified `waitForCallContext` complexity and inline pattern inconsistencies
- Manual line-by-line review of full diff

File: Test/Framework/TestWebApplication/e2e-todo-tests.js (hunk 1 above)
Comment (gautam-achieveai) [reply Test/Framework/TestWebApplication/e2e-todo-tests.js:212]: Good catch — adopted your suggestion. Split into `waitForCallContext` (non-null) and `waitForNewCallContext(page, oldTraceId)`. All call sites updated. Pushed in 04aac86b.

File: Test/Framework/TestWebApplication/e2e-todo-tests.js (hunk 2 above)
Comment (gautam-achieveai) [reply Test/Framework/TestWebApplication/e2e-todo-tests.js]: Fixed — replaced `waitForSelectorCount` with `waitForTodoTitle(page, s, 'Read a book')` in both drag-drop tests (My Day and Important). This waits for the specific dragged todo instead of a generic item count. Pushed in 04aac86b.

File: Test/Framework/TestWebApplication/e2e-todo-tests.js (hunk 3 above)
Comment (gautam-achieveai) [reply Test/Framework/TestWebApplication/e2e-todo-tests.js]: Fixed — renamed `sel` to `selector` in both `waitForFolderHeader` and the inline value-change wait. Pushed in 04aac86b.

**Review by gautam-achieveai — COMMENTED** [review]
**[Gautam's review bot]** PR !22 Re-Review (Iteration 3) — Replace fixed sleeps in TodoApp E2E suite with state-based waits

## Verdict: ✅ APPROVE

All 3 review findings from iteration 2 have been addressed correctly in `04aac86b`:

| Previous Finding | Status |
|------------------|--------|
| **[MEDIUM]** `waitForCallContext` silent fallback | ✅ Split into `waitForCallContext` (non-null) + `waitForNewCallContext(page, oldTraceId)` — clean, no string parsing |
| **[MEDIUM]** Drag-drop race condition | ✅ Both tests now use `waitForTodoTitle(page, s, 'Read a book')` — waits for specific dragged todo |
| **[LOW]** `sel` → `selector` naming | ✅ Renamed in `waitForFolderHeader` and inline value-change wait |

### Verification Summary
- All 10 call sites correctly use the two new functions (6x `waitForCallContext`, 4x `waitForNewCallContext`)
- Zero `waitForTimeout()` calls remain in the file
- No new issues introduced in this iteration
- Playwright API signatures (`waitForFunction(predicate, arg, options)`) used correctly throughout

**Linked Issue**: #9

Good work on the clean iteration — each fix is focused and correct.
